script-engine: "javascript"
message:
  prefix: "&b道具自选&f "
  help:
    - "&b道具自选命令帮助"
    - "&3/%c give <玩家> <道具编号> [数量] &6给予玩家道具"
    - "&3/%c save <展示物品编号> &6添加一个展示物品"
    - "&3/%c forceOpen <玩家> <道具编号> &6强制打开自选道具"
    - "&3/%c reload &6重载插件配置文件"
  too-much: "超过该礼盒可选数量."
  insufficient: "选择奖励数量不足."
  null-item: "请手持一个物品."
  wrong-item-id: "请输入一个物品编号."
  wrong-prop-id: "请输入一个道具编号."
  player-offline: "目标玩家不在线."
  item-exists: "该物品编号已存在."
  save: "成功存储物品."
  view-not-exists: "目标展示页面不存在."
  pls-held-item: "手上的物品不是一个有效的礼盒."
  gotten: "成功领取奖励."
  give: "成功给予玩家 &b%player% &f道具."
  not-met-condition: "你无法使用这个礼盒."
  reload: "插件配置重载完成."