name: EasyGift
main: com.blank038.easygift.EasyGift
depend:
  - AyCore
  - PlaceholderAPI
  - NBTAPI
softdepend:
  - NashornJs
version: ${project.version}
api-version: 1.13
commands:
  easygift:
    aliases:
      - egift
    description: Command for EasyGift.